# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9223492f585c0a76006d61ce2552c7b23f0d436cbe54f7d06cafac92ccb93c49007497d0c165e736939a45087faa3ebb6675257027aae0bc52f940348e7cee08

test:
  secret_key_base: 83fe370a1b3196b8600b492a37905e0f6e9d1c4265261755d682571c1692f2d5537ab2f963f318e656ba4193133881f73d4146556534f43de75d359533dfbbe3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
